### ISSUE TITLE
Pod is invalid

### ISSUE THREAD

**Issue by av0c0der** [dreymonde/Time#1]
Can't install due to error: 
> Missing required attribute `summary`.

Seems like you didn't upload this Pod to Cocoapods specs repo.

**Comment by dreymonde** [comment]
Hi! Yes, I haven’t configured CocoaPods yet. I’ll ping you when it’s done :)

**Comment by dreymonde** [comment]
@Jauzee now available on CocoaPods as
```
pod "TimeIntervals"
```

**Comment by av0c0der** [comment]
Thank you!
